package com.agentweave.shared.audit;

public enum AuditEventType {

    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PERMISSION_DENIED,
    TOOL_PERMISSION_DENIED,
    USER_PROFILE_UPDATED,
    USER_PASSWORD_RESET,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_PERMISSION_CHANGED,
    ROLE_STATUS_CHANGED,
    WORKFLOW_APPROVAL_CREATED,
    WORKFLOW_APPROVAL_APPROVED,
    WORKFLOW_APPROVAL_REJECTED,
    WORKFLOW_APPROVAL_DENIED
}
